### ISSUE TITLE
[1.7.9 Issue] Problems using PingTab

### ISSUE THREAD

**Issue by Zilacon** [Poweruser/MinetickMod#11]
So i gound this plugin called PingTab. And since my players CONSTANTLY keep blaming their crappy internet lag on my server i figured this would be perfect to show them how bad their connection is to the server.

So heres the plugin: http://dev.bukkit.org/bukkit-plugins/pingtab/

And here is what its spamming on the console:
[11:53:41 WARN]: [PingTab] Task #49 for PingTab v1.2 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_7_R1/entity/CraftPlayer
    at br.net.hexafun.PingTab.PingTab$2.run(PingTab.java:279) ~[?:?]
    at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[minetick179.jar:git-Bukkit-1.7.9-R0.2-85-gab98788]
    at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) [minetick179.jar:git-Bukkit-1.7.9-R0.2-85-gab98788]
    at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:659) [minetick179.jar:git-Bukkit-1.7.9-R0.2-85-gab98788]
    at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:262) [minetick179.jar:git-Bukkit-1.7.9-R0.2-85-gab98788]
    at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:607) [minetick179.jar:git-Bukkit-1.7.9-R0.2-85-gab98788]
    at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:509) [minetick179.jar:git-Bukkit-1.7.9-R0.2-85-gab98788]
    at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [minetick179.jar:git-Bukkit-1.7.9-R0.2-85-gab98788]

So is this a problem with PingTab or MineTick?

**Comment by PixelKitsune** [comment]
Pingtab is outdated.

**Comment by Zilacon** [comment]
How is it out dated? http://dev.bukkit.org/bukkit-plugins/pingtab/files/9-ping-tab-v1-3-1/
There is the 1.7.9 version.

**Comment by PixelKitsune** [comment]
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_7_R1/entity/CraftPlayer

Looks like the author used a 1.7.2 version of craftbukkit to compile it

**Comment by Poweruser** [comment]
The file of v1.3.1 that you have is not the one, that is currently available for download on the PingTab project site. I just too a look at its source by decompiling it and it correctly references the  v1_7_R3 package. Just download it again.
The one you have was, like sk8er said, built with a 1.7.2 version of the server.

**Comment by Zilacon** [comment]
Alright my bad, i downloaded it from spigotmc.org first then looked it up on dev bukkit for more info.
